---
title: "Cancer genes"
output: html_document
---

```{r}
library(glue, include.only = "glue")
library(here, include.only = "here")
library(readr, include.only = c("read_tsv", "read_csv", "cols"))
library(tidyr)
library(tibble)
library(purrr)
library(stringr)
library(dplyr)
```

```{r lists}
read_symbol <- function(x) {
  # in the case of 'umccr.tsv', this just names its second column 'X2'
  read_tsv(x, col_names = c("symbol"), col_types = "c")
}

folder <- here("ngs_utils/reference_data/key_genes")
dir.exists(folder)

# read in single-column files
genes <- tibble::tribble(
  ~alias, ~path,
  "predispose", "predispose_genes.txt",
  "az300", "az_key_genes.300.txt",
  "cacao", "cacao.txt",
  "umccr", "umccr.tsv",
  "pmcc", "PMCC.genes",
  "ts500", "TS500.genes",
  "tempus", "TEMPUS.genes",
  "famcan", "familial_cancer.genes"
) |>
  mutate(path = file.path(folder, "sources", path)) |>
  tibble::deframe() |>
  as.list() |>
  purrr::map_dfr(read_symbol, .id = "sources") |>
  select(sources, symbol)
```

```{r ncg}
# http://ncg.kcl.ac.uk/
ncg_tsgonco  <- file.path(folder, "sources/NCG6_tsgoncogene.tsv") |>
  read_tsv(col_types = "ccccll") |>
  mutate(
    sources = "NCG_known",
    ncg_fu = stringr::str_detect(cgc_annotation, "fusion")
  ) |>
  rename(
    ncg_og = NCG6_oncogene,
    ncg_ts = NCG6_tsg
  ) |>
  select(sources, symbol, starts_with("ncg_"))

genes_ncg <-  bind_rows(genes, ncg_tsgonco)

ncg_cancer <- file.path(folder, "sources/NCG6_cancergenes.tsv") |>
  read_tsv(col_types = cols(.default = "c"))
ncg_cancer_other <- ncg_cancer |>
  filter(type != "Known Cancer") |>
  group_by(symbol) |>
  summarise(
    ncg_n = n(),
    type = str_c(unique(type), collapse=", "),
    cancer_type = str_c(unique(cancer_type), collapse=", "),
    primary_site = str_c(unique(primary_site), collapse=", "),
    method = str_c(unique(method), collapse=", ")
  ) |>
  arrange(desc(ncg_n)) |>
  filter(ncg_n >= 3)

genes_ncg <- genes_ncg |>
  bind_rows(ncg_cancer_other |>
              mutate(sources = "ncg_other") |>
              select(symbol, sources, ncg_n))

genes_ncg |> filter(sources == "ncg_known")
```

```{r cancermine}
cancermine <- file.path(folder, "sources/cancermine_collated.tsv") |>
  read_tsv(col_types = cols(.default = "c", citation_count = "i"))

cancermine_prep <- cancermine |>
  mutate(symbol = gene_normalized,
         cm_cite = citation_count,
         cm_og = role == "Oncogene",
         cm_ts = role == "Tumor_Suppressor",
         cm_driver = role == "Driver") |>
  filter(citation_count >= 3 | symbol == "SMURF1") |>
  select(symbol, starts_with("cm_")) |>
  group_by(symbol) |>
  summarise(sources = "cancermine",
            cm_pub = n(),
            cm_total_cite = sum(cm_cite),
            cm_og = mean(cm_og),
            cm_ts = mean(cm_ts),
            cm_driver = mean(cm_driver)) |>
  filter(cm_pub >= 2)
# cancermine_prep |> arrange(cm_pub, cm_total_cite)

genes_cm <- genes_ncg |>
  bind_rows(cancermine_prep)

genes_cm |> filter(sources == "cancermine")
```

```{r oncokb}
oncokb <- file.path(folder, "sources/oncoKB_cancerGeneList.txt") |>
  read_tsv(col_types = cols(.default = "c"))
oncokb_prep <- oncokb |>
  transmute(
    symbol = `Hugo Symbol`,
    oncokb = ifelse(`OncoKB Annotated` == "Yes", T, F),
    msk_impact = ifelse(`MSK-IMPACT` == "Yes", T, F),
    msk_heme = ifelse(`MSK-HEME` == "Yes", T, F),
    foundation_one = ifelse(`FOUNDATION ONE` == "Yes", T, F),
    foundation_one_heme = ifelse(`FOUNDATION ONE HEME` == "Yes", T, F),
    vogelstein = ifelse(`Vogelstein` == "Yes", T, F)
  ) |>
  tidyr::pivot_longer(cols = -symbol, names_to = "sources", values_to = "yes") |>
  filter(yes) |>
  select(-yes)

oncokb_prep |> filter(sources == "oncokb")

genes_ok <- genes_cm |> bind_rows(oncokb_prep)
```

```{r cosmic}
cosmic <- bind_rows(
  file.path(folder, "sources/CancerGeneCensus_Tier1.tsv") |> read_tsv(),
  file.path(folder, "sources/CancerGeneCensus_Tier2.tsv") |> read_tsv())
cosmic_prep <- cosmic |>
  transmute(
    symbol = `Gene Symbol`,
    sources = ifelse(Tier == 1, 'cosmic1', 'cosmic2'),
    cos_germ = Germline == "yes",
    cos_ts = `Role in Cancer` == 'TSG',
    cos_og = `Role in Cancer` == 'oncogene',
    cos_fu = `Role in Cancer` == 'fusion')

genes_cos <- genes_ok |> bind_rows(cosmic_prep)
genes_cos |> filter(str_detect(sources, "cosmic"))
```

```{r tsg}
tsgene_ts <- file.path(folder, "sources/arthur/TSGene2-oncogenes.genes") |> read_symbol()
tsgene_og <- file.path(folder, "sources/arthur/TSGene2-tumour-suppressors.genes") |> read_symbol()
genes_tsg <- genes_cos |> mutate(
  tsg_ts = symbol %in% tsgene_ts,
  tsg_og = symbol %in% tsgene_og
)
genes_tsg
```

```{r hmf_fusions}
hmf_pairs <- read_csv("../fusions/knownFusionPairs.csv")
hmf_prom_head <- read_csv("../fusions/knownPromiscuousFive.csv")
hmf_prom_tail <- read_csv("../fusions/knownPromiscuousThree.csv")
hmf_fus_genes <- bind_rows(
    hmf_pairs |> select(symbol = T_gene),
    hmf_pairs |> select(symbol = H_gene),
    hmf_prom_head |> select(symbol = gene),
    hmf_prom_tail |> select(symbol = gene)
  ) |>
  distinct() |>
  mutate(
    sources = 'HMF_fusions',
    hmf_fu = T
  )

genes_hmf <- genes_tsg |> bind_rows(hmf_fus_genes)
```
Counting each source:

```{r}
all_genes <- genes_hmf
all_genes |> count(sources)
```

```{r summarise}
genes_sum <- all_genes |>
  group_by(symbol) |>
  summarise(
    n = n(),
    sources = str_c(sources, collapse = "|"),
    ncg = str_detect(sources, "ncg_known"),
    cosm1 = str_detect(sources, "cosmic1"),
    cancermine = str_detect(sources, "cancermine"),
    cacao = str_detect(sources, "CACAO"),
    umccr = str_detect(sources, "UMCCR"),
    haem = str_detect(sources, "HAEM"),
    germ = any(cos_germ, na.rm = T) | str_detect(sources, "CPSR"),

    ncg_ts = any(ncg_ts, na.rm = T),
    cm_ts = sum(cm_ts, na.rm = T),
    cos_ts = any(cos_ts, na.rm = T),
    tsg_ts = any(tsg_ts, na.rm = T),

    ncg_og = any(ncg_og, na.rm = T),
    cm_og = sum(cm_og, na.rm = T),
    cos_og = any(cos_og, na.rm = T),
    tsg_og = any(tsg_og, na.rm = T),

    driver = sum(cm_driver, na.rm = T),
    cos_fu = any(cos_fu, na.rm = T),
    hmf_fu = any(hmf_fu, na.rm = T),
    ncg_fu = any(ncg_fu, na.rm = T)
  ) |>
  mutate(
    tumorsuppressor = ncg_ts | cm_ts > 0 | cos_ts | tsg_ts,
    oncogene = ncg_og | cm_og > 0 | cos_og | tsg_og,
    fusion = hmf_fu | cos_fu | ncg_fu
  ) |>
  mutate(
    tier1 = ncg | cosm1 | cancermine | cacao | umccr | haem | driver | n >= 4,  # well curated cancer genes
    is_key = tier1 | germ | n >= 2       # + not so confident + predisposition + known fusions
  ) |>
  select(-ends_with("_og"), -ends_with("_ts"), -starts_with("ncg_"))

genes_hmf |> filter(symbol |> str_detect("SMU"))
```

Annotating with APPRIS canonical transcripts:

```{r add_appris}
# these are in the vladsavelyev/bed_annotation GitHub repo
repo <- "https://raw.githubusercontent.com/vladsavelyev/bed_annotation/6f3735/bed_annotation/ensembl"
appris_cnames <- c('appris_symbol', 'ensg', 'enst', 'tr_name', 'annotation')
appris_hg19 <- glue("{repo}/hg19/appris_data.principal.txt") |>
  read_tsv(col_names = appris_cnames, col_types = cols(.default = "c"))
appris_hg38 <- glue("{repo}/hg38/appris_data.principal.txt") |>
  read_tsv(col_names = appris_cnames, col_types = cols(.default = "c"))

appris_hg19_sum <- appris_hg19 |>
  filter(str_detect(annotation, 'PRINCIPAL')) |>
  group_by(appris_symbol) |>
  summarise(PRINCIPAL_hg19 = str_c(enst, collapse = ','))

appris_hg38_sum <- appris_hg38 |>
  filter(str_detect(annotation, 'PRINCIPAL')) |>
  group_by(appris_symbol) |>
  summarise(PRINCIPAL_hg38 = str_c(enst, collapse = ','))

genes_sum_appris <- genes_sum |>
  left_join(appris_hg19_sum, by = c('symbol' = 'appris_symbol')) |>
  left_join(appris_hg38_sum, by = c('symbol' = 'appris_symbol'))

# checking genes that miss the canonical transcript:
genes_sum_appris |> filter(is.na(PRINCIPAL_hg19), is_key)
# 33 genes
genes_sum_appris |> filter(is.na(PRINCIPAL_hg38), is_key)
# 31 genes
genes_sum_appris |> filter(is.na(PRINCIPAL_hg19) & is.na(PRINCIPAL_hg38), is_key)
# 14 genes
```

Comparing to the previous version:

```{r compare_to_previous}
prev = read_tsv("umccr_cancer_genes.latest.tsv")

(added   <- genes_sum_appris |> filter(is_key, !symbol %in% prev$symbol))
(removed <- genes_sum_appris |> filter(symbol %in% prev$symbol, !is_key))

# play around:
genes_sum_appris |> filter(is_key) |> filter(tier1)
genes_sum_appris |> filter(is_key) |> filter(cosm1 & cancermine & !ncg)  # 0
genes_sum_appris |> filter(is_key) |> filter(ncg) |> arrange(desc(n))
genes_sum_appris |> filter(is_key & !tumorsuppressor & !oncogene & !fusion & !germ) |> arrange(desc(n))
genes_sum_appris |> filter(cos_fu & !hmf_fu)
```

Writing results to the latest files and to the archive:

```{r write_results}
library(lubridate)
# tsv with metadata:
genes_sum_appris |> filter(is_key) |> select(-is_key) |> write_tsv(str_c("archive/umccr_cancer_genes.", lubridate::today(), ".tsv", sep = ""))
genes_sum_appris |> filter(is_key) |> select(-is_key) |> write_tsv(str_c("umccr_cancer_genes.latest.tsv", sep = ""))
# plain list of genes:
genes_sum_appris |> filter(is_key) |> .$symbol |> write_lines(str_c("archive/umccr_cancer_genes.", lubridate::today(), ".genes", sep = ""))
genes_sum_appris |> filter(is_key) |> .$symbol |> write_lines(str_c("umccr_cancer_genes.latest.genes", sep = ""))
# plain list of only tumor suppressor genes:
genes_sum_appris |> filter(tumorsuppressor) |> .$symbol |> write_lines(str_c("archive/umccr_cancer_genes.tsgenes.", lubridate::today(), ".genes", sep = ""))
genes_sum_appris |> filter(tumorsuppressor) |> .$symbol |> write_lines(str_c("umccr_cancer_genes.tsgenes.latest.genes", sep = ""))
```





```{r compare_to_arthurs_list, eval = F}
added <- genes_sum |> filter(keep, !symbol %in% umccr$symbol)
removed <- genes_sum |> filter(symbol %in% umccr$symbol, !keep)

predispose |> mutate(
  umccr = symbol %in% genes_sum$symbol
)

# # exlore sources of added genes
# genes4 |> filter(symbol %in% added$symbol) |> arrange(symbol)
#
# # exlore sources of removed genes
# genes4 |> filter(symbol %in% removed$symbol) |> arrange(symbol)
added
removed
```
Checking how much value AZ300 brings. 11 genes.

```{r checking_az300, eval = F}
genes_sum |> filter(str_detect(sources, "AZ300"), n == 2) |> select(sources, symbol, n, is_key)
# is_key  n
# <lgl>   <int>
# FALSE  	41	
```

Comparing COSMIC germline and PCGR predispose: PCGR includes _all_ COSMIC germline genes

```{r germline, eval = F}
genes_tsg |>
  group_by(symbol) |>
  summarise(
    cos_germ = any(cos_germ, na.rm = T),
    predispose = any(str_detect(sources, "predispose"))
  ) |> count(cos_germ, predispose)
```

```{r eval = F}
genes_sum |>
  filter(symbol == "MYC") |>
  select(-tsg_ts, -tsg_og, -cm_driver)
```
```{r}
  # group_by(symbol) |>
  # summarise(
  #   n = n(),
  #   cm_ts = str_c(cm_ts),
  #   cm_og = str_c(cm_og),
  #   ncg_og = ncg_og,
  #   ncg_ts = ncg_ts,
  #   ncg_fu = ncg_fu)

# Selecing:
# - Cancermine (we pre-selected at least 2 publications with at least 3 citations)
# - ncg_known
# - CancerGeneCensus_Tier1
# - At least in 2 of of clinical panels: MSKC-IMPACT, MSKC-HEME, PMCC, TS500, TEMPUS, FoundationONE, FoundationHEME
# - At least 2 sources from CancerGeneCensus_Tier2, AZ300, OncoKB-Annotated, FamilialCancer, Oncogenes, TumourSuppressors
genes4 |> count(sources, sort = T)
# Annotating:
# - oncogene if ncg_og or mc_og >= 0.1
# - tumor_suppressor if ncg_ts or cm_ts >= 0.1
# - fusion if ncg_fu
genes4 |> count(ncg_ts)
# The result is a list of 1387 genes:
#   - 1114 genes in at least one clinical panel
#   - 194 genes in database that are not in any of used clinical panel
#   - 79 genes in ensemble (2+) lists that are not included above

# | any(cm_og, na.rm = T) | any(cm_og, na.rm = T))
```

```{r}
genes_sum |> count(cm_ts > 0, ncg_ts, tsg_ts)
genes_sum |> filter(cm_ts > 0, ncg_ts, tsg_ts)
genes_sum |> count(cm_og > 0, ncg_og, tsg_og)
genes_sum |> filter(symbol == 'BRCA1')
```

```{r eval = F}
cancermine_oncogene <- cancermine |> filter(role == "Oncogene")
ncg_oncogene <- ncg_tsgonco |> filter(NCG6_oncogene == 1)
cancermine_oncogene
ncg_oncogene
```

```{r eval = F}
ncg_cancer$symbol |> unique() |> length()
```

```{r eval = F}
ncg_tsgonco$symbol |> unique() |> length()
```

```{r eval = F}
intersect(umccr, unique(ncg_cancer$symbol)) |> unique() |> length()
```
```{r eval = F}
intersect(umccr, ncg_tsgonco$symbol |> unique()) |> unique() |> length()
```
```{r eval = F}
setdiff(unique(ncg_tsgonco$symbol), umccr) |> unique()
```

```{r eval = F}
ncg_cancer_collapsed <- ncg_cancer |>
  group_by(symbol) |>
  summarise(
    n = n(),
    type = str_c(unique(type), collapse=", "),
    cancer_type = str_c(unique(cancer_type), collapse=", "),
    primary_site = str_c(unique(primary_site), collapse=", "),
    method = str_c(unique(method), collapse=", ")
  )

ncg_cancer_collapsed |> filter(symbol %in% umccr) |> arrange(desc(n)) |> filter(n <= 8)
```


```{r eval = F}
ncg_cancer |> filter(symbol == "MKL1")
```
